services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    container_name: postgres
    ports:
      - 5433:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-crud-app
    environment:
      - PORT=${PORT}
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./src:/app/src